name: build
on: [push, pull_request]

jobs:
  build-amd64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - run: go version

      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev gcc pkg-config libwayland-dev libx11-dev \
            libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev \
            libxcursor-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: build binaries
        shell: bash
        run: |
          mkdir -p bin
          for d in $(find ./cmd -type d -mindepth 1 -maxdepth 1); do
            go build -o bin/$(basename $d) $d
          done

      - name: upload archive
        uses: actions/upload-artifact@v2
        with:
          name: aightreader-${{ matrix.os }}-amd64
          path: "bin/*"
